#============================================================#
##                 Spring Config                            ##
#============================================================#
spring:
  jackson:
    default-property-inclusion: non-null
  
#============================================================#
##                 Log Config                               ##
#============================================================#
logging:
  level:
    osuapi: DEBUG