#============================================================#
##                 Log Config                               ##
#============================================================#
logging:
  level:
    osuapi: DEBUG