---
name: Codecov Report

on: [push, pull_request]

jobs:
  build:
    name: Codecov Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 8
          distribution: "temurin"

      - name: Install dependencies
        run: mvn install -DskipTests=true -Dgpg.skip -B -V

      - name: Run tests and collect coverage
        run: mvn -B test

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
